# Generated by Django 3.2.11 on 2022-04-11 05:46

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0003_user_model_extend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 13, 5, 46, 53, 807577, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
