# Generated by Django 3.2.12 on 2022-05-04 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 13, 16, 56, 472028, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
